services:
  gitea:
    image: gitea/gitea:latest
    volumes:
      - ./gitea:/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    command: tunnel --config /root/.cloudflared/config.yml run
    volumes:
      - ~/.cloudflared:/root/.cloudflared
