version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"


  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    command: tunnel --config /root/.cloudflared/config.yml run
    volumes:
      - ~/.cloudflared:/root/.cloudflared
